
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'DEC59D1C47F1D54FE99FCEE5A59F26D3'
    
_lr_action_items = {'AND':([5,6,9,10,19,20,21,22,],[-2,-3,11,-4,-6,-7,-8,-5,]),'LPAR':([3,4,7,11,12,13,14,],[4,4,4,4,4,4,4,]),'XOR':([5,6,9,10,19,20,21,22,],[-2,-3,12,-4,-6,-7,-8,-5,]),'IFF':([5,6,9,10,19,20,21,22,],[-2,-3,13,-4,-6,-7,-8,-5,]),'PROP':([3,4,7,11,12,13,14,],[5,5,5,5,5,5,5,]),'LNAME':([0,],[1,]),'LITERAL':([3,4,7,11,12,13,14,],[6,6,6,6,6,6,6,]),'COLON':([1,],[3,]),'NOT':([3,4,7,11,12,13,14,],[7,7,7,7,7,7,7,]),'RPAR':([5,6,10,15,16,17,18,19,20,21,22,],[-2,-3,-4,19,20,21,22,-6,-7,-8,-5,]),'OR':([5,6,9,10,19,20,21,22,],[-2,-3,14,-4,-6,-7,-8,-5,]),'$end':([2,5,6,8,10,19,20,21,22,],[0,-2,-3,-1,-4,-6,-7,-8,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([3,4,7,11,12,13,14,],[8,9,10,15,16,17,18,]),'label':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> label","S'",1,None,None,None),
  ('label -> LNAME COLON formula','label',3,'p_label','ply_label_parser.py',19),
  ('formula -> PROP','formula',1,'p_formula_prop','ply_label_parser.py',23),
  ('formula -> LITERAL','formula',1,'p_formula_literal','ply_label_parser.py',27),
  ('formula -> NOT formula','formula',2,'p_formula_not','ply_label_parser.py',31),
  ('formula -> LPAR formula OR formula RPAR','formula',5,'p_formula_or','ply_label_parser.py',35),
  ('formula -> LPAR formula AND formula RPAR','formula',5,'p_formula_and','ply_label_parser.py',39),
  ('formula -> LPAR formula XOR formula RPAR','formula',5,'p_formula_xor','ply_label_parser.py',43),
  ('formula -> LPAR formula IFF formula RPAR','formula',5,'p_formula_iff','ply_label_parser.py',47),
]
